### ISSUE TITLE
How the highway_map.csv created

### ISSUE THREAD

**Issue by rahulnkadam** [udacity/CarND-Path-Planning-Project#27]
I am new to these topic self driving car. I am curious about how was the Highway_map.csv data created which include x,y,s,dx & dy. Searched a lot but everyone has used the same data and no description about it. What if I want to create my own map in reality so how can I make the similar data which is in the highway_map.csv. Thank you in advance.

**Comment by mvirgo** [comment]
@awbrown90 Do you know the answer for this?

**Comment by mvirgo** [comment]
So it looks like the way to do this is just grabbing this information from the simulator by lane. The simulator gives you x, y, s, d and yaw, from which you can also calculate dx and dy. You could essentially just drive down the middle of each lane and have this information get exported to a file.

Closing this one out due to age, but feel free to re-open if you have further questions.
