### ISSUE TITLE
NextWaypoint() error in checking if WPT is behind ego vehicle

### ISSUE THREAD

**Issue by AeroGeekDean** [udacity/CarND-Path-Planning-Project#31]
https://github.com/udacity/CarND-Path-Planning-Project/blob/8d1ec77dd6180d812b900a3a08d926f37c90c3c0/src/main.cpp#L77

It's my understand that this line is to check to see if the bearing-off-bow to the next waypoint (WPT) is behind the ego vehicle, which would be beyond 90 deg from nose of ego.

Thus this should be
`if (angle > pi()/2)`

instead of
`if (angle > pi()/4)`
???

**Comment by mvirgo** [comment]
Yeah, it looks like you are correct. Interestingly enough, when I checked this solution against my old code as a student, it looked to resolve a difficulty my implementation had when the car got boxed in on all sides (and would try to "push" others out of the way sometimes :) ).

(Finally) fixed by 32d2cb9.
