### ISSUE TITLE
Add uWebSockets into git module

### ISSUE THREAD

**Issue by Horki** [udacity/CarND-Path-Planning-Project#51]
as example, and update bash scripts and README

```
[submodule "uWebSockets"]
	path = uWebSockets
	url = https://github.com/uWebSockets/uWebSockets
```

**Comment by MrGeislinger** [comment]
I think I had a related issue when building uWebSockets on a Mac. Since this project is using a deprecated version (See the [Dependencies section](https://github.com/udacity/CarND-Path-Planning-Project/blob/9519f02a5f91ed58a605f44b0fb1a27fe53943ab/README.md#dependencies) where we refer to commit `e94b6e1`.

I think I have a quick fix from my [repo](https://github.com/MrGeislinger/Self-Driving-Path-Planning/issues/2) where I simply modified the `install-mac.sh` script.

I think I'll put in a pull request to fix this tonight.
